---
title: "Draw matrix"
author: "H.Luo"
date: "2016-12-23"
output: html_document
---
```{r}
#Draw a matrix
matrix2list<-function(mat){
  nRow=dim(mat)[1];
  nCol=dim(mat)[2];
  if(nRow!=nCol){
    return(FALSE)
  }else{
    n=nRow;
    lis<-matrix(NA,nrow=n*n,ncol=3);
    colnames(lis)<-c("row","col","value");
    counter=1;
    for(i in 1:n){
      for(j in 1:n){
        lis[counter,]<-c(i,j,mat[i,j]);
        counter=counter+1;
      }
    }
    return(lis)
  }
}
mat1<-rbind(
  c(0.1,0,0.4,0.5),
  c(0,0,1,0),
  c(0,1,0,0),
  c(0.2,0.3,0.1,0.4)
)
lis1<-matrix2list(mat1)
```

```{r}
plotmatrix<-function(mat,heat=F,dig=6){
  require(ggplot2);
  lis<-matrix2list(mat);
  adp_size<-sqrt(1/dim(lis)[1])*16.18;
  ggdat<-as.data.frame(lis);
  if(heat==F){
    grp<-ggplot(data=ggdat)+
        #geom_point(aes(x=col,y=row))+
        geom_text(aes(x=col,
                      y=row,
                      label=as.character(round(value,digits=dig) )
                      ),
                  size=adp_size
                  )+
        theme_void()+
        theme(legend.position="none");
    return(grp)
  }else{
  grp<-ggplot(data=ggdat)+
        #geom_point(aes(x=col,y=row))+
        geom_tile(aes(x=col,
                      y=row,
                      fill=value
                      )
                  )+
        scale_fill_continuous(breaks=seq(0,1,by=0.1))+
        theme_void();
    return(grp)    
  }
}

g1<-plotmatrix(mat1%*%mat1,heat=T);
g1
```

```{r}
evolvematrix<-function(mat,steps,heat=F,dig=6){
  mat0<-mat;
  mat.current<-mat0;
  for(n in 1:steps){
    mat.current<-mat.current%*%mat;
    grp.current<-plotmatrix(mat.current,heat=heat,dig=dig);
    print(grp.current)
    Sys.sleep(0.1);
  }
}
evolvematrix(mat1,steps=10,heat=T)
```

```{r}
animationmatrix<-function(mat,steps,heat=F,conPATH=FALSE,interval=0.01,dig=6){
  require(animation);
  if(conPATH!=FALSE){
    ani.options(convert=conPATH);
  }
  saveGIF(evolvematrix(mat=mat,steps=steps,heat=heat,dig=dig),
          interval=interval,
          outdir=getwd()
          )
}
library(animation)
animationmatrix(mat1,steps=20,heat=F)
```
```{r}
mat2<- matrix(c(0,1/3,2/3, 0, 0, 1, 1, 0, 0), nrow = 3, byrow = T)
animationmatrix(mat2,steps=20,heat=T,interval=0.1)
mat3<-rbind(
  c(0.1,0,0.4,0.5),
  c(0,0.1,0.9,0),
  c(0.45,0.05,0.05,0.45),
  c(0.2,0.3,0.1,0.4)
)
animationmatrix(mat3,steps=20,heat=T)
```

