#The data set I used is generated by perturbing 
#[x,y,x^2+y^2]
library(rgl)
r<-seq(0,2*pi,length.out=100)
x<-c(1*sin(r),10*sin(r),20*sin(r))
y<-c(1*cos(r),10*cos(r),20*cos(r))
l<-length(x)
color<-c(rep("red",length(r)),rep("blue",length(r)),rep("green",length(r)))
z<-c();
for(i in 1:l){
  z[i]<-x[i]^2+y[i]^2+rnorm(1,0,10);
}
plot3d(x,y,z,col=color)
rgl.snapshot("3D.png","png") 
#Data set plotted in 3-dim
for(i in 1:l){
  z[i]<-0;
}
plot3d(x,y,z,col=color)
rgl.snapshot("2D.png","png") 
#Data set plotted in 2-dim